
version: 2
updates:
- package-ecosystem: docker
  directory: "/docker"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

